name: Telegram Daily Bot

on:
  schedule:
    - cron: "7 3 * * *"
    - cron: "7 15 * * *"
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram message
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          if [ "${{ github.event.schedule }}" = "0 3 * * *" ]; then
            MESSAGE='🌞 Доброе утро, Венера!

Сегодня поблагодари за:

💛 Новые возможности, которые принесёт этот день.
🌿 Здоровье и силы двигаться к своим целям.
🤝 Людей, которые поддерживают тебя и помогают расти.

Сделай паузу на минуту и добавь ещё 3 своих благодарности. Пусть это станет хорошим началом дня. ✨'
          else
            MESSAGE='🌙 Как прошёл твой день?

🟢 Отлично
😊 Хорошо
😐 Нейтрально
🔴 Ужасно'
          fi

          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
          -d chat_id="${CHAT_ID}" \
          --data-urlencode text="$MESSAGE"
